# Development configuration overrides
# This file overrides settings from _config.yml for local development

# Override API configuration for local development
api:
  base_url: "http://localhost:3001"
  waitlist_endpoint: "/api/waitlist"

# Override site URL for local development
url: "http://localhost:4000"

# Enable verbose output for debugging
verbose: true

# Disable some plugins that might cause issues in development
plugins:
  - jekyll-feed
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
